name: lww_crdt
description: A simple last-write-wins crdt that uses vector clocks and timestamps
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  dart_code_metrics: ^3.3.6
  coverage: ^1.0.3
