name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      - name: Lint code
        run: dart analyze
      - name: Run Code Metrics
        run: dart pub run dart_code_metrics:metrics --reporter=github lib
      - name: Run tests and generate coverage data
        run: dart test --coverage coverage
      - name: Convert coverage data
        run: dart run coverage:format_coverage -i coverage/test/ -l -o coverage/coverage.lcov
      - name: Upload code coverage data
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
          name: lww_crdt
          token: ${{ secrets.CODECOV_TOKEN }}
